### ISSUE TITLE
InvalidOperationException during console rendering

### ISSUE THREAD

**Issue by cr0wquill** [LykosAI/StabilityMatrix#111]
![Image 001](https://github.com/LykosAI/StabilityMatrix/assets/144185161/55d7401f-4dec-49a7-bc96-23523294469a)

Hi, any suggestions here? Connection times out and WebUI closes shortly after this message appears.

**Comment by mohnjiles** [comment]
Hi, this is a known issue we are working on, it seems to be caused by some web UIs that add a second progress bar to the console output. If you are using Automatic1111, you can try disabling/unchecking this option while we work on a fix: 
![image](https://github.com/LykosAI/StabilityMatrix/assets/33761/26a9039c-3963-4e3b-825b-10cf75c65f20)
