### ISSUE TITLE
Comfyui extra_model_paths hard coded

### ISSUE THREAD

**Issue by WSJUSA** [LykosAI/StabilityMatrix#130]
It seems the management of the model paths for comfyui hard codes _possible_ paths in extra_model_paths.yaml

This limits being able to define new directories or subdirectories, as the yaml reader rewrites it on every instantiation of Comfyui

in this process:
https://github.com/LykosAI/StabilityMatrix/blob/2d0965a4d35a9371c62f22e307b88551efccf368/StabilityMatrix.Core/Models/Packages/ComfyUI.cs#L220

maybe this could be more flexible to not overwrite new paths, or have a way to add new paths to a config

thanks

**Comment by mohnjiles** [comment]
Hi there, you should certainly be able to add your own extra paths to the yaml file, are you saying we're overwriting the *entire* file or just that `stability-matrix` section? If the former, that's a bug. You should be able to add extra sections to the yaml as [shown here](https://github.com/comfyanonymous/ComfyUI/blob/master/extra_model_paths.yaml.example), we should only be overwriting the section named `stability-matrix`.

Also, in the newer 2.4.x versions, we've added an option to install packages without symlinks or config modifications - you can try using Symlinks or just set it to None if you'd rather manage it yourself.
<img width="339" alt="image" src="https://github.com/LykosAI/StabilityMatrix/assets/33761/7042bf68-16ad-4e7b-b5d3-6528b99c841d">

We will be adding an option to switch these at runtime instead of having to reinstall the package to switch the "Shared Folder Strategy".

**Comment by mohnjiles** [comment]
Scratch that, just tried it myself - will get this fixed in the next version. Thanks for the report!
