### ISSUE TITLE
API Rate limit?

### ISSUE THREAD

**Issue by KarlVanSnail** [LykosAI/StabilityMatrix#163]
### Discussed in https://github.com/LykosAI/StabilityMatrix/discussions/162

<div type='discussions-op-text'>

<sup>Originally posted by **KarlVanSnail** October  2, 2023</sup>

![image](https://github.com/LykosAI/StabilityMatrix/assets/6966591/42995534-f70a-4cde-84c7-741b3811ebff)

</div>

**Comment by sh1ny** [comment]
Having the same issue.

**Comment by ionite34** [comment]
Will look to fix this to not crash soon, but it still will prevent package information fetch / installs. Mainly due to the very low public API rate limit GitHub has (60 requests per hour), we already have local memory caching as well... 

But at the moment if this happens try waiting until the next hour mark where the rate limit will be reset.

**Comment by ionite34** [comment]
Implemented better error handling to not crash on these rate limits in latest versions.
