### ISSUE TITLE
Ability to download SD base models and others type of models

### ISSUE THREAD

**Issue by eephyne** [LykosAI/StabilityMatrix#164]
I was just wondering if an option/tab/whatever could exist to allow download the base models from Stability. You can't find them on civitai and if you download them throught an interface it'll be only available for this interface (exepction if you move the files yourself afterward).

Like Model download of comfyui-manager , it could also allow to download others type of models like controlnet/sam/bbox/etc… 

thanks for your time :p

**Comment by Void2258** [comment]
Yeah I was going to suggest that in addition to the Civit AI integration, Hugging Face is also need for the more general base stuff. 

Hugging Face hosts most things lower level/universal things like SD1.5 and XL base models, controlnets, ip adapters, VAEs, etc., while civit is the place for custom and individualized stuff. With just civit, users have to know where to go and what to get for many things the programs in SM usually just automatically get for the user (and using the built in scripts would put them in such a way that only that program can see them, defeating the point of SM), so many people won't know what to do about these.

**Comment by Void2258** [comment]
I have been trying to deal with this since my last post without luck. There is no good repository or list for this, as most places assume your package just comes with these set up already. Everything I can find is all about getting ADDITIONAL models (ie from civit) with the assumption you just already have all the control nets, upscalers, etc. We desperately need a way to handle this; 80% of functions are effectively disabled because they have no models to work with.

**Comment by ionite34** [comment]
Base model download with huggingface collections since been implemented in newest versions: https://github.com/LykosAI/StabilityMatrix/releases
