### ISSUE TITLE
About the same huge copies of VENV folders...

### ISSUE THREAD

**Issue by gendheruwo** [LykosAI/StabilityMatrix#216]
Previously I had several custom versions of WebUI (including the tools like kohyass etc) with their own installed extensions at once. But they were still able shared the same VENV, Loras and Checkpoints from the same directories without any crashes or bugs, maybe because the my VENV downloaded on the same device with the same settings to launch each WebUI and the tools.

My problem is the commandline args to set VENV_DIR doesn't works in Stability Matrix, I suggest the VENV folder can be placed in the Assets directory, maybe on the next version I hope, so my storage doesn't swell with same VENV folders. I'm not an expert in Python coding, just changing what I can from several sources that I have downloaded for my own use.

Thank you for developing the Stability Matrix, hopefully improvement on the next version.

**Comment by ionite34** [comment]
Mainly the reason for individual venvs is that the different packages / versions of packages usually require different / conflicting dependencies. It's possible we can use the inherit site packages feature of virtualenv to install some primary packages like PyTorch into the root embedded Python rather than venvs, but that will prevent you from testing, say, PyTorch v2.1.0 in a new package while keeping your current one running v2.0.1

Not really sure how we can do this cleanly
