### ISSUE TITLE
dGPU + more performant eGPU > only dGPU detected by installation procedure

### ISSUE THREAD

**Issue by TheManBe** [LykosAI/StabilityMatrix#235]
I'm ready to install Stability Matrix to give it a go, but the initial screen that appears, only finds my (weaker) internal laptop dGPU (NVIDIA M1000M), and NOT the RTX 3090 in my eGPU enclosure.

So I'm postponing going further  :)

I have FOOOCUS and AUTOMATIC1111 installed and working with the eGPU no problem, so it's a detection issue in the Stability Matrix.

How can I "force" it into recognizing the correct GPU?

**Comment by ionite34** [comment]
The initially setup screen just shows the first identified GPU, but we internally store all identified ones. In this case it shouldn't matter for installation because both use CUDA installs, you can proceed and disregard that initial message.

We'll try to add an option to select GPU in cases if you have both AMD/Nvidia and it'll affect the default install libraries.

**Comment by TheManBe** [comment]
ah ok... Thanks for getting back.

TBH, I think it's kinda confusing when it only shows the "first", because that gives the impression that it's missing any other ones. Adding some clarification to that screen wouldn't hurt.  :)
