### ISSUE TITLE
Extremely High GPU Usage on Package Pages and When Images Appear in UI

### ISSUE THREAD

**Issue by centomila** [LykosAI/StabilityMatrix#250]
I've noticed abnormal GPU usage whenever an image is displayed, even though no other packages are running.

Stability Matrix 2.6.0
Windows 11 PRO
nVidia RTX 4060TI 16GB

Launch Page / Settings Page: 0%
![image](https://github.com/LykosAI/StabilityMatrix/assets/26800547/30a21e01-c54e-4898-b8fb-b0c32a42b1f3)

Inference Page: 15/20%
![image](https://github.com/LykosAI/StabilityMatrix/assets/26800547/71d22058-fea7-4ffd-b335-96417bf32230)

Packages: 20/30%
![image](https://github.com/LykosAI/StabilityMatrix/assets/26800547/0a101269-2149-454f-99bf-d68e46e77017)

Checkpoints:
![image](https://github.com/LykosAI/StabilityMatrix/assets/26800547/e832ff2d-f812-4aa4-bd65-0e973bc5d88d)

![image](https://github.com/LykosAI/StabilityMatrix/assets/26800547/3da4df93-c8c5-4af5-bb84-9177026b3400)

**Comment by Sylgrio** [comment]
This problem is still existent on the newest version, 2.7.9, when on "Packages" page, the Stability Matrix.Avalobia and Desktop Windows Manager start using the GPU, each using around 25 or 30%.

This is happening on Windows 10, newest update, with no Packages launch, the Stability Matrix program simply opened. The only package that I have installed is the automatic 1111.

**Comment by ionite34** [comment]
This is likely due to our use of the native Win 11 rendering API for hardware acceleration. It shouldn't conflict with the SD packages which use different computation cores. We also are using the fairly new open source UI framework https://github.com/AvaloniaUI/Avalonia, which is improving in performance 
 with new developments so this should improve over time. 
 
If you're worried you can try launching with `--disable-gpu-rendering` and see if that makes a difference in generation performance, but some UI features like transparency and shadows won't show correctly.
