### ISSUE TITLE
add support for .MP4 & .gif preview images for checkpoints and loras

### ISSUE THREAD

**Issue by halr9000** [LykosAI/StabilityMatrix#271]
Civitai has many such, and whenever you scroll past them in the manager, you see this error: "failed to load image"

![image](https://github.com/LykosAI/StabilityMatrix/assets/18482/5c77dac2-47ca-4406-be0a-546cc0957c06)

Quick research shows that the first image in each of these (eg [this one](https://civitai.com/models/138179?modelVersionId=152647)) is animated.

Edit: turns out the animation was an .MP4 so have updated the title

**Comment by halr9000** [comment]
Working with a model library containing animations is getting increasingly annoying, given the popularity of SVD etc making it easier for people to create these short animations. CivitAI is also starting to make it easier to share video. Screenshots of working with such a model in the downloader and manager screens:
![image](https://github.com/LykosAI/StabilityMatrix/assets/18482/91f7fbeb-91d6-49ef-a880-86660ecbce50)
![image](https://github.com/LykosAI/StabilityMatrix/assets/18482/ac90a719-855b-4c3a-b0d5-449aa5c7ec13)
![image](https://github.com/LykosAI/StabilityMatrix/assets/18482/587a77fd-ecdb-45fb-a685-8765ecea3d6a)
![image](https://github.com/LykosAI/StabilityMatrix/assets/18482/f6065120-f206-42e1-a1a1-7dddea176c97)

Would be a quick workaround to simply use one of the alternate model images from civitAI.

**Comment by halr9000** [comment]
Cross-posted to discord https://discord.com/channels/1115555685476868168/1188514961127903302

**Comment by mohnjiles** [comment]
The issue with picking a "non-video" is that CivitAI returns the file extension as `.jpeg` 100% of the time, even when it's not: https://github.com/civitai/civitai/issues/769. If this isn't fixed by the time we're ready to launch v2.8, we may have some other workarounds...

However, we are working on .gif and .webp support to go with img2vid in Inference, will see if we can add mp4 to the list too :)
