### ISSUE TITLE
REQ: Checkpoints & Model Browser organization features

### ISSUE THREAD

**Issue by halr9000** [LykosAI/StabilityMatrix#280]
Stuffing a lot into this one, if you want me to split it out, happy to do that but it's all related to me. 

Here are some top of mind improvements and tweaks:

- Rename Checkpoints tab to Model Manager? It's really for managing all kinds of models, not just literal .ckpt files.
- Add sorting by: modified date, size, name. Ascending and descending. This will help to find new things to experiment with, old things to get rid of, or big files to consider when running low on space.
- Add filters for all kinds of model metadata, and apply it across multiple model types when applicable. For example, as a serial experimenter, I want to work with similar techniques at once, so I want to filter on base model combability. Checkpoint, Lora, TI, CNet, VAE are all specific to certain base models (1.5, SDXL etc), so it would be nice to quickly show only those and hide the rest.
- Add refresh button in case I do some file changes elsewhere
- Allow for subfolders and help to manage those as well

I have 468 models and could really use some help managing this. :D 
![Screenshot 2023-11-23 110320](https://github.com/LykosAI/StabilityMatrix/assets/18482/1037b40a-c103-427a-a0b6-610aecc658b1)

Here's a shot from sd-ux which has refresh and sorting.

![image](https://github.com/LykosAI/StabilityMatrix/assets/18482/f87d14bd-9d66-4d96-823e-5bf01bc4074e)

Some similar issues include:
- https://github.com/LykosAI/StabilityMatrix/issues/98 
- https://github.com/LykosAI/StabilityMatrix/issues/234

**Comment by hakaserver** [comment]
I think this is one very underestimated feature yet to be implemented. A proper model organizer with subfolders, classification and full info and sample gallery backup would be the most important feature of Stability Matrix for me. Especially since Civitai's API already allows all this information to be easily retrieved.

Also, the current info.json the model browser creates when downloading a model is not very good:

- It downloads some of the model info from Civitai, but does not include essential info like Trigger Words.
- The description might not be easily readable since it maintains its html formatting but also keeps every unicode character in its code format, potentially making the text a sea of \uXXXX codes.
- It doesn't take advantage of a1111 function of reading an accompanying .json file containing "description", "sd version", "activation text", "preferred weight" and "notes" which can be filled with information parsed from Civitai. The ideal being creating the mentioned .json file and a separate .info file containing all available info parsable.
- The info downloaded alongside the model could also include all image samples prompts and neg prompts set by the uploader, which sometimes is the only place where the trigger word is informed (also, no sample image is currently downloaded).

I think one great example of a proper model manager I could mention is the a1111 extension sunnyark/civitai-shortcut. It is great at managing models and saving every info available, but it suffers from being restricted by gradio's clunkiness. The creator also recently informed it can no longer maintain it due to personal reasons, unfortunately.

**Comment by halr9000** [comment]
Great additions. 

> I think one great example of a proper model manager I could mention is the a1111 extension sunnyark/civitai-shortcut. It is great at managing models and saving every info available, but it suffers from being restricted by gradio's clunkiness. The creator also recently informed it can no longer maintain it due to personal reasons, unfortunately.

And this is why I would love to offload all of this type of problem to SM project who already SO CLOSE (and further along in many other ways)!

**Comment by gisu** [comment]
What would be nice for the checkpoints:

- the checkpoint page should be scrollable when dragging and dropping (is the folder to which the model is to be moved, outside the viewport you can't currently get to it) - you can select models and then either group them in a new folder, or add them to an existing one
