### ISSUE TITLE
Model Browser Download Failure

### ISSUE THREAD

**Issue by Vesperindustrial** [LykosAI/StabilityMatrix#291]
Quite a few times seemingly with no rhyme or pattern the download fails instantly with the error:

(AggregateException) One or More errors occurred. (The request message was already sent. Cannot send the same request message).

Retrying doesnt work either. A common user where this happens is https://civitai.com/user/Stable_Yogi but its definitely not exclusive to them. Downloading manually from civitai works, as does from the civitai brower extension in a1111

**Comment by ionite34** [comment]
This is due to the model requiring CivitAI login to download (A recent feature model authors can enable). We've added a better error for this, as well as an Accounts settings page where you can connect your CivitAI account to download those models in v2.7.0, which should be released soon. 

If you're interested in supporting us, we're releasing development builds on our [Patreon](https://www.patreon.com/StabilityMatrix/posts?filters%5Btag%5D=Release) as we work on them
