### ISSUE TITLE
Inference feature request

### ISSUE THREAD

**Issue by an90ray** [LykosAI/StabilityMatrix#340]
can we get denoise setting (0.7 by default now) and clip skip for Inference?

**Comment by ionite34** [comment]
It should be adjustable for Image To Image projects, for Text To Image defaulting to 0.7 was a bug that should now be fixed in https://github.com/LykosAI/StabilityMatrix/releases/tag/v2.7.4 to use 1.0 denoise instead. 

We could look to add a settings menu (like for HiresFix steps) to enable denoise for the base samplers though.

**Comment by an90ray** [comment]
thx. denoise 1.0 for t2image now in 2.7.4. what about "CLIP Set Last Layer" settings?
