### ISSUE TITLE
(IMPORT FAILED) ReActor Node for ComfyUI

### ISSUE THREAD

**Issue by clovnix** [LykosAI/StabilityMatrix#344]
Good day,

I am having problems using the ReActor Node for ComfyUI. It says that the import failed. I have found some solutions on how to fix this, which involves changes in the "python_embedded" folder. But this is not present in this installation.

How can I fix this?

**Comment by jasttme** [comment]
use StabilityMatrix\Packages\ComfyUI\venv\Scripts\python.exe instead python_embeded\python.exe

**Comment by nothingness6** [comment]
> use StabilityMatrix\Packages\ComfyUI\venv\Scripts\python.exe instead python_embeded\python.exe

Hi, Jasttme. 
I have the same issue. Could you explain the details? So, what do you mean exactly? How to use the python.exe? 
Once you launch Stability Matrix, you can launch ComfyUI in it. You don't need to use pythone.exe at all.

**Comment by jasttme** [comment]
> Hi, Jasttme.
> I have the same issue. Could you explain the details? So, what do you mean exactly? How to use the python.exe?
> Once you launch Stability Matrix, you can launch ComfyUI in it. You don't need to use pythone.exe at all.
> Should I fix the code or something?

You should replace 'python_embeded" with real path to python.exe at ComfyUI folder. Open the ComfyUI folder and find python.exe there. The path to this file will need to be copied and replaced with python_embeded

Example: my ComfyUI is located at C:\StabilityMatrix\Packages\ComfyUI. python.exe located at  C:\StabilityMatrix\Packages\ComfyUI\venv\Scripts\python.exe. Instead of command `python_embeded\python.exe -V,` execute command `C:\StabilityMatrix\Packages\ComfyUI\venv\Scripts\python.exe -V`. Do the same with other commands. In my case, these were the commands listed here https://github.com/Gourieff/comfyui-reactor-node?tab=readme-ov-file#troubleshooting
