### ISSUE TITLE
StabilityMatrix broken after Update to 2.7.4

### ISSUE THREAD

**Issue by MaximumBlast** [LykosAI/StabilityMatrix#350]
After Updating i cannot start it anymore.....

![Screenshot 2023-12-21 174059](https://github.com/LykosAI/StabilityMatrix/assets/60583831/156d7f02-0ef5-4b00-96af-4e4d4ab8f5be)

**Comment by MaximumBlast** [comment]
Running on Windows10... not sure what version i came from, just installed it last week though.

**Comment by MaximumBlast** [comment]
Reinstalled the whole thing now....

**Comment by ionite34** [comment]
Seems this is related to an issue of the `settings.json` getting written as blank during app shutdown due to the OS file buffer not completely flushing, the short delay between old app shutdown and new launch might be causing this to be more likely to occur.

We're working on a fix for the file writing but at the moment if this happens again try backing up and deleting the `settings.json` file in the Data folder.

**Comment by MaximumBlast** [comment]
ok, thanks for your reply!

**Comment by drdancm** [comment]
I found it useful to make a backup copy of the .json file prior to updating.

**Comment by ionite34** [comment]
We've improved the settings file writing safety on NTFS so this should be less likely to occur now, feel free to remake the issue if there are changes.
