### ISSUE TITLE
Feature Request: StableSwarmUI

### ISSUE THREAD

**Issue by mgsnell** [LykosAI/StabilityMatrix#352]
I would like to suggest the addition of StableSwarmUI to the choices of installable packages in Stability Matrix (https://github.com/Stability-AI/StableSwarmUI), it would provide another choice to the front end of ComfyUI.
mgsnell

**Comment by CodeAlexx** [comment]
Please add Swarm!!

**Comment by jdroo** [comment]
bump o3o

**Comment by OLH21** [comment]
I understand that it would interfere with inference but considering that swarm is an official free tool by Stability this could be a really good add for stability matrix,

**Comment by mohnjiles** [comment]
I'm not sure where people are getting this idea that StableSwarm would somehow "interfere" or "compete" with us - and I don't mean to call you out specifically, just want to get this out there - the primary reason it hasn't been implemented is because:

- The licensing was some proprietary Stability-AI license (which has since been rectified, and is now under the much-more-open MIT license)
- We didn't want to bloat the app with a bunch of .NET SDKs, hoping that their dev team would release a more "finished" version that relied on only the .NET runtimes instead.


Since we have been receiving a lot more interest in Swarm recently, we've decided that hard-drive space be damned, the users want it so we'll install the necessary prerequisites.

StableSwarm has been in the Patreon dev builds for a few days now, and is scheduled to release alongside lllyasviel's Stable Diffusion WebUI Forge in v2.9.0.

**Comment by OLH21** [comment]
thanks for the clarification, and thanks for adding it )) this is all great news
