### ISSUE TITLE
Unexpected Error Occurred when launching application

### ISSUE THREAD

**Issue by ju2au** [LykosAI/StabilityMatrix#353]
This issue suddenly occurred out of the blue. What can I do? Do I have to reinstall the whole thing?

See attached screenshot:

![Unexpected Error Occurred](https://github.com/LykosAI/StabilityMatrix/assets/66828823/3ddc5b99-882c-4e12-a772-4da8f17dc662)

**Comment by ionite34** [comment]
In your selected data directory, can you check if the `settings.json` file is empty or otherwise contains some invalid value? Make a backup of it and remove it, then it should create a new valid one on startup.

The issue of the `settings.json` getting overwritten with invalid / empty values seems to be an issue during app shutdown saving and the windows file buffer not flushing on NTFS, still working on a fix for that.
