### ISSUE TITLE
Deleted output folder

### ISSUE THREAD

**Issue by Calad0** [LykosAI/StabilityMatrix#409]
Hi. I've been using StabilityMatrix for a few months and today I decided to install everything in a new location. 

Problem: When I uninstalled ComfyUI from older drive (through StabilityMAtrix launcher), the output folder was also deleted and now I can't find it anywhere. In fact, I can't find none of the uninstalled files, even with data recovery software.

In short, HELP!

Regards

Edit: I know it says it deletes all files within the folder. I thought I had moved it. My question is how are the files deleted, because data recovery software doesn't find anything.

**Comment by Naveronasis** [comment]
Jesus Christ guys warn somebody before you securely erase outputs god damn it. I'm in the same boat, lost everything.

**Comment by ionite34** [comment]
Our current uninstall removes the package folder, if you weren't using shared outputs that includes the default output folders for generated images. I think we included a sufficient warning for that here: 
![image](https://github.com/LykosAI/StabilityMatrix/assets/13956642/9f348344-900e-41e4-8d06-b5ff4d1781c2)

The delete functions are the standard ones from .NET, there's nothing else we can use and it's not a special secure delete:
https://github.com/LykosAI/StabilityMatrix/blob/main/StabilityMatrix.Core/Models/FileInterfaces/DirectoryPath.cs#L132

If there's some other way to better rephrase the pre-uninstall warning let us know, otherwise closing this for now.
