### ISSUE TITLE
macOS build

### ISSUE THREAD

**Issue by ionite34** [LykosAI/StabilityMatrix#45]
Currently most of the backend should be compatible

Todo:
- [x] Investigate how file access is affected by sandboxing and use the Avalonia bookmarks API for file access
- [x] Add embedded asset variants for macos 
- [x] Figure out macOS for Github CI builds

## Relevant links
https://docs.avaloniaui.net/docs/distribution-publishing/macos

**Comment by send2cloud** [comment]
Still not working in Mac M2 studio

**Comment by lukemun** [comment]
This would be a great feature!

**Comment by AFLYPA** [comment]
I’m really looking forward to using it on Mac soon. When will it be available? Thanks!

**Comment by viking1304** [comment]
@ionite34 I have just stumbled upon this issue. Since I made an [updated step-by-step guide for the A1111 installation on Mac](https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/5461#discussioncomment-7738578), which was tested on M1 and iMac with Radeon, I hope you can find some relevant info there to help you with this task. The most common issues are parameters that do not work with the stable torch version, and some errors introduced with changes in torchvison development version. You can also find [the timing results](https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/5461#discussioncomment-7830815) I got while testing SDXL on my Mac with different parameters (if that is also relevant for you). Just remember that all Macs use metal, so do not try to install ROC on Macs with Radeon

**Comment by indudanu** [comment]
looking forward

**Comment by ionite34** [comment]
Update: Finally got our build CIs working with code signing and notarizing, ([since Apple made that mandatory after macOS 10.15](https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution)) so we're starting to include macOS releases from [v2.8.0-dev.3](https://www.patreon.com/posts/v2-8-0-dev-3-95588321)

Depending on how testing goes we're looking forward to have macOS builds and auto-updates ready for v2.8.0 release. Currently have ComfyUI and InvokeAI packages working with MPS acceleration on Apple silicon machines, but will try to get other packages working too.

![image](https://github.com/LykosAI/StabilityMatrix/assets/13956642/94100df8-c105-488b-8483-4e8228bd19ca)

![image](https://github.com/LykosAI/StabilityMatrix/assets/13956642/49faff65-d258-43a9-8012-fb9a08d5b466)

**Comment by huameiwei-vc** [comment]
Looking forward to it, when we can use it？

**Comment by huameiwei-vc** [comment]
Wish I could add a web proxy option, I can only use clash to get to certain sites!

**Comment by tian-jie** [comment]
looking forward to the latest release!

**Comment by allanhoi** [comment]
is stability matrix available on macOS yet?

**Comment by jorge-campo** [comment]
> is stability matrix available on macOS yet?

So far, only via Patreon: https://www.patreon.com/posts/v2-8-0-dev-3-95588321

**Comment by zencowboy007** [comment]
Yes, looking for to this on Mac!  Thank you for your contributions!!

**Comment by xdfnet** [comment]
looking forward to the latest release!

**Comment by ionite34** [comment]
Released in https://github.com/LykosAI/StabilityMatrix/releases/tag/v2.8.0
