### ISSUE TITLE
Feature request: StableSwarm inference support

### ISSUE THREAD

**Issue by OkGamez313** [LykosAI/StabilityMatrix#535]
If at all possible, it would be cool to use the same gui for swarm

**Comment by ionite34** [comment]
Since StableSwarm is also using backends like A1111 / ComfyUI (which Inference uses) I don't think it makes a huge difference. Most of the work currently is in new UI components for Inference in .NET. Inference using a different backend will still be the same UI and the same features we made, perhaps with speed differences.
