### ISSUE TITLE
[FEATURE REQUEST] Install & Stay at specific Github Commits

### ISSUE THREAD

**Issue by Koitenshin** [LykosAI/StabilityMatrix#701]
With the [recent Forge announcement](https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/801) bringing Forge's future into question, I'd like StabilityMatrix to be able to go back to commits that the user can specify, similar to how we can change versions of specific Python Libraries.

We should also be able to freeze the commit there, so updates are ignored.

#670

**Comment by LadyFlames** [comment]
wouldnt it be better to make it so what we can switch Branches as well even when the WebUI itself is already installed because currently Forge is being turned into a Forge Space as we saw with the forge announcement and the aftermath of it  they asked if people would switch to A1111 Dev Branch or stay with Forge Dev2 branch to help with the Development of features but eventually Forge Dev 1 branch and Master Branch will be merged with A1111 thats when A1111 2.0 launches and people are still hoping for Forge 2 someday

**Comment by Koitenshin** [comment]
Being able to switch branches, or install a new instance based on that branch would be nice. You could have your main version of A1111 and the dev version at the same time under one easy manager.

People have checked out the dev version of A1111 and while it is faster, it is still extremely lackluster compared to ComfyUI and Forge. A1111 needs to recode the backend regarding memory management and refuses to do so.

**Comment by thekarmakazi** [comment]
I would love to use dev branch, but there's no way to switch.
