### ISSUE TITLE
Can't install Fooocus - pip version problem?

### ISSUE THREAD

**Issue by ghost** [LykosAI/StabilityMatrix#711]
```
WARNING: Ignoring version 0.2.5 of torchsde since it has invalid metadata:
Requested torchsde==0.2.5 from https://files.pythonhosted.org/packages/73/8d/efd3e7b31ea854d0bd6886aa3cf44914adce113a6d460850af41ac1dd4dd/torchsde-0.2.5-py3-none-any.whl has invalid metadata: .* suffix can only be used with `==` or `!=` operators
    numpy (>=1.19.*) ; python_version >= "3.7"
           ~~~~~~~^
Please use pip<24.1 if you need to use this version.
ERROR: Could not find a version that satisfies the requirement torchsde==0.2.5 (from versions: 0.2.5, 0.2.6)
ERROR: No matching distribution found for torchsde==0.2.5
```

**Comment by spammcahid** [comment]
I have the same issue.

`Unpacking resources
Unpacking resources
Download Complete
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu121
Collecting torch==2.1.0
  Using cached https://download.pytorch.org/whl/cu121/torch-2.1.0%2Bcu121-cp310-cp310-win_amd64.whl (2473.9 MB)
Collecting torchvision==0.16.0
  Using cached https://download.pytorch.org/whl/cu121/torchvision-0.16.0%2Bcu121-cp310-cp310-win_amd64.whl (5.8 MB)
Collecting torchsde==0.2.5
  Using cached torchsde-0.2.5-py3-none-any.whl.metadata (748 bytes)
WARNING: Ignoring version 0.2.5 of torchsde since it has invalid metadata:
Requested torchsde==0.2.5 from https://files.pythonhosted.org/packages/73/8d/efd3e7b31ea854d0bd6886aa3cf44914adce113a6d460850af41ac1dd4dd/torchsde-0.2.5-py3-none-any.whl has invalid metadata: .* suffix can only be used with `==` or `!=` operators
    numpy (>=1.19.*) ; python_version >= "3.7"
           ~~~~~~~^
Please use pip<24.1 if you need to use this version.
ERROR: Could not find a version that satisfies the requirement torchsde==0.2.5 (from versions: 0.2.5, 0.2.6)
ERROR: No matching distribution found for torchsde==0.2.5
Could not install Fooocus (StabilityMatrix.Core.Exceptions.ProcessException: pip install failed with code 1: 'Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu121\r\nCollecting torch==2.1.0\r\n  Using cached https://download.pytorch.org/whl/cu121/torch-2.1.0%2Bcu121-cp310-cp310-win_amd64.whl (2473.9 MB)\r\nCollecting torchvision==0.16.0\r\n  Using cached https://download.pytorch.org/whl/cu121/torchvision-0.16.0%2Bcu121-cp310-cp310-win_amd64.whl (5.8 MB)\r\nCollecting torchsde==0.2.5\r\n  Using cached torchsde-0.2.5-py3-none-any.whl.metadata (748 bytes)\r\nWARNING: Ignoring version 0.2.5 of torchsde since it has invalid metadata:\r\nRequested torchsde==0.2.5 from https://files.pythonhosted.org/packages/73/8d/efd3e7b31ea854d0bd6886aa3cf44914adce113a6d460850af41ac1dd4dd/torchsde-0.2.5-py3-none-any.whl has invalid metadata: .* suffix can only be used with `==` or `!=` operators\r\n    numpy (>=1.19.*) ; python_version >= "3.7"\r\n           ~~~~~~~^\r\nPlease use pip<24.1 if you need to use this version.\r\nERROR: Could not find a version that satisfies the requirement torchsde==0.2.5 (from versions: 0.2.5, 0.2.6)\r\nERROR: No matching distribution found for torchsde==0.2.5\r\n'
   at StabilityMatrix.Core.Python.PyVenvRunner.PipInstall(ProcessArgs args, Action`1 outputDataReceived)
   at StabilityMatrix.Core.Models.Packages.Fooocus.InstallPackage(String installLocation, TorchVersion torchVersion, SharedFolderMethod selectedSharedFolderMethod, DownloadPackageVersionOptions versionOptions, IProgress`1 progress, Action`1 onConsoleOutput)
   at StabilityMatrix.Core.Models.Packages.Fooocus.InstallPackage(String installLocation, TorchVersion torchVersion, SharedFolderMethod selectedSharedFolderMethod, DownloadPackageVersionOptions versionOptions, IProgress`1 progress, Action`1 onConsoleOutput)
   at StabilityMatrix.Core.Models.PackageModification.InstallPackageStep.ExecuteAsync(IProgress`1 progress)
   at StabilityMatrix.Core.Models.PackageModification.PackageModificationRunner.ExecuteSteps(IReadOnlyList`1 steps))`

**Comment by N1k145** [comment]
I have the same issue and a workaround:

Click on the dots at Fooocus in Packages
Then Python Packages 
Select pip
Select 24.0 in the drop-down an click the downgrade button

Then restart the installation

**Comment by bsdesigner** [comment]
I'm sorry, but I'm not quite sure where to look for Python Packages:
![Знімок екрана 2024-06-24 135415](https://github.com/LykosAI/StabilityMatrix/assets/36730003/49f94b1d-a080-4319-b571-5ee52562d7db)

**Comment by spammcahid** [comment]
I finally managed to install Fooocus. First I tried @N1k145's workaround but unfortunately the UI didn't show any options when I clicked on the dots. @
![StabilityMatrix_7XNTwq1tYa](https://github.com/LykosAI/StabilityMatrix/assets/62016917/7b479bf3-9ef3-49fd-a384-f44093726be4)

I then manually imported Fooocus with default settings and Stability Matrix created a Foocus tab in the Packages menu. After that I tried to update Fooocus manually but it didn't work in the Packages tab. I then copied a clean Fooocus build to the "Stability Matrix\Data\Packages" disk location and tried to update it again with Stability Matrix and it worked.
![StabilityMatrix_96i80ElqcT](https://github.com/LykosAI/StabilityMatrix/assets/62016917/0e374d2e-a41c-48f3-994b-3819cec197ca)

**Comment by N1k145** [comment]
@spammcahid maybe I missed the point where I clicked on import

When I clicked on "update" (or check for update I don't remember exactly), I think it provided me with an Update for Fooocus so that I could run the installation again.

**Comment by nyukers** [comment]
> I have the same issue and a workaround:
> 
> Click on the dots at Fooocus in Packages Then Python Packages Select pip Select 24.0 in the drop-down an click the downgrade button
> 
> Then restart the installation

Restart installation? So Uninstall Fooocus again?
