### ISSUE TITLE
SwarmUI not able to load

### ISSUE THREAD

**Issue by Don-Schlaich** [LykosAI/StabilityMatrix#716]
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-E:\Stability does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

I've gone in and uninstalled and tried to re-install SwarmUI since the switch over, but I keep getting this message every time I've tried to start the interface.

**Comment by Targren** [comment]
`Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-E:\A1111 does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.`

I'm getting the same error. 

It's worth noting that the actual path is "E:\A1111 Web UI\StabilityMatrixData\..."  So it's cutting off at the first space.

**Comment by ionite34** [comment]
Should be fixed in https://github.com/LykosAI/StabilityMatrix/releases/tag/v2.11.3
