### ISSUE TITLE
Trojan? :D

### ISSUE THREAD

**Issue by MarianQQQ** [LykosAI/StabilityMatrix#736]
Hi, maybe this is a weird question, but can I be nervous about this?)

![photo_2024-06-29_23-38-13](https://github.com/LykosAI/StabilityMatrix/assets/98672339/527595cb-8af2-4eb0-b2dd-171fc0db2162)

**Comment by ionite34** [comment]
Is this something new with our last update or flagged the same for previous builds? iirc some detection algorithms flag us just due to python library files (getpip and venv) which are embedded in that dll. (But that has been the same for the past year or so of updates). They're not needed for Linux and macOS so builds for those platforms don't include those python files.

**Comment by nyukers** [comment]
Zillya ?

**Comment by Koitenshin** [comment]
Those two specific vendors on VirusTotal are notorious for giving off false positives.
