### ISSUE TITLE
Moving checkpoints selectively to external drive?

### ISSUE THREAD

**Issue by fbauer-kunbus** [LykosAI/StabilityMatrix#771]
Is there a way to move certain rarely used checkpoints to an external drive while keeping the most important ones on the same drive where Stability Matrix is installed? Can it be done with using additional symbolic links on my windows system? Is this something that can be configured from within Stability Matrix? Can someone point to a solution?

**Comment by skelsan** [comment]
You can make a symbolic link using Windows tools.
1. Create a directory on an external disk where you plan to store rarely used models.
2. Move your models to this directory.
3. In Windows, open a command prompt (cmd, not the modern PowerShell) with administrator privileges.
One easy way to do this: Press Win+R to open the "Run" box. Type "cmd" into the box and then press Ctrl+Shift+Enter to run the command as an administrator. Click "Yes" when the UAC warning appears.
At the command prompt that opens, you type the following:

mkdir /D "destination" "source"

"destination" - path to the directory with models in the StabilityMatrix.
"source" - path to the directory with models on your external disk.

For example, in my case, disk L is the external disk, disk F is the internal disk where StabilityMatrix is installed, SD15LCM is the directory where rarely used models are stored.

mklink /D "F:\StabilityMatrix\Models\StableDiffusion\SD15LCM" "L:\ModelX\SD15LCM"

**Before executing the command, please note that there must not be a directory in the destination directory with the name you gave to the rare models directory, otherwise you will get an error. Also pay attention that the path in the source and destination do not end with a slash sign.**
