### ISSUE TITLE
Python update

### ISSUE THREAD

**Issue by Beogradski** [LykosAI/StabilityMatrix#801]
Guys, how can i update matrix built-in python for comfy ui?

**Comment by crmbz0r** [comment]
Unfortunately, it doesn't seem like you can when using StabilityMatrix..
I've tried around a few things but once you start ComfyUI, it will override any python venv that is not the 3.10.11 from the StabilityMatrix environment.
You might have to install a second instance of ComfyUI's portable version, since this one comes with embedded python 3.11.9.
Still not 3.12, but better than 3.10 ^^

**Comment by DmytroSokhach** [comment]
Oh, I have the same question. How to update to ComfyUI recommended Python 3.12?
I've had long path from manual installs to StabilityMatrix and don't want go back 🥹

**Comment by mohnjiles** [comment]
Changing the base Python version is not available at this time, but is something we plan to add in the future.
