### ISSUE TITLE
Not All Models Arent Showing up in the CivitAI Browser 

### ISSUE THREAD

**Issue by LadyFlames** [LykosAI/StabilityMatrix#82]
some model versions arent Showing up on the integrated  Civit AI Browser/Model Downloader  Like Fantexi for example 0.9beta is in there  but not 0.8C which is what i need tbh if that makes sense could be the case for many other models as well

**Comment by mohnjiles** [comment]
Hi, thanks for the report! 

In this case it looks like there are two different models named similarly uploaded to CivitAI, https://civitai.com/models/131601 and https://civitai.com/models/18427. The first model does not have any version other than 0.9 as you say, however the second one does have those versions. 

I think the issue here may be that the "correct" version is marked as NSFW, and only shows up if you have the "Show NSFW Context" box checked. Could you select that option in the Model Browser and see if it shows up then?

**Comment by LadyFlames** [comment]
thanks

**Comment by mohnjiles** [comment]
Feel free to open another issue if you have any other problems. Thanks!
