### ISSUE TITLE
[Bug] WebUI Forge updates force torch to downgrade

### ISSUE THREAD

**Issue by Nyksia** [LykosAI/StabilityMatrix#822]
For some reason whenever the app updates Forge UI, it keeps downgrading the torch to 2.1 version. I've checked the requirements file for Forge, and it doesn't specify a version it should be, so it seems to be something on Stability's side that keeps doing that.

**Comment by BSoD38** [comment]
Yeah, I have this as well, seems like Stability Matrix hardcoded torch to use 2.1.2, even though WebUI Forge recommends using 2.3.1. Also, there seems to be an issue with Stability Matrix forgetting dependency package version overrides when you update, which makes the feature kind of useless since the packages update almost every day.

**Comment by mohnjiles** [comment]
Sorry about that, we've updated it to the recommended 2.3.1 version [as of v2.11.7](https://github.com/LykosAI/StabilityMatrix/releases/tag/v2.11.7)

**Comment by Nyksia** [comment]
> Sorry about that, we've updated it to the recommended 2.3.1 version [as of v2.11.7](https://github.com/LykosAI/StabilityMatrix/releases/tag/v2.11.7)

@mohnjiles That does technically fix that, but since Forge doesn't specify the version it has to use for torch, is there a possibility of just letting it install the latest, as Forge is supposed to? Or maybe some way for a user to be able to stop it from overriding the package versions that were manually changed?

**Comment by mohnjiles** [comment]
> > Sorry about that, we've updated it to the recommended 2.3.1 version [as of v2.11.7](https://github.com/LykosAI/StabilityMatrix/releases/tag/v2.11.7)
> 
> @mohnjiles That does technically fix that, but since Forge doesn't specify the version it has to use for torch, is there a possibility of just letting it install the latest, as Forge is supposed to? Or maybe some way for a user to be able to stop it from overriding the package versions that were manually changed?
> 
> EDIT: Also noticed it doesn't just override the version, it overrides what CUDA version the torch package is for, so if you're using a different CUDA version, it will keep installing the wrong version too.

From the readme:
![image](https://github.com/user-attachments/assets/41a1d872-d73f-4d0e-89e7-a0b6d5ba2d07)

That said, we are working on a way to allow people to specify their preferred version during installation.
Also pretty much everyone should be using the CUDA 12.1 versions since 12.4 is still in beta.

**Comment by Nyksia** [comment]
That's reasonable, it is just that as someone who prefers to use whatever's fastest even at cost of stability, it is rather tedious to manually reinstall torch every time to match the one required for CUDA 12.4 after every update, and with latest xformers I also had no issues using that combo.
Having more control over versions of packages we have would really be welcome, at least for more "advanced" users. Perhaps just limiting the recommended torch version installation to the initial install and not the update, unless the recommended torch changes. But ideally it should just be an opt out option.
